package com.yourcompany;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * demoService service = new demoService();
 * DemoDelegate portType = service.getDemoPort();
 * portType.myHelloworld(...);
 * </pre>
 * 
 * </p>
 * 
 */
//202.120.199.112
@WebServiceClient(name = "demoService", targetNamespace = "http://yourcompany.com/", wsdlLocation = "http://202.120.199.112/JWInterface/demoPort?wsdl")
public class DemoService extends Service {

	private final static URL DEMOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.yourcompany.DemoService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.yourcompany.DemoService.class.getResource(".");
			url = new URL(baseUrl,
					"http://202.120.199.112/JWInterface/demoPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://202.120.199.112/JWInterface/demoPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DEMOSERVICE_WSDL_LOCATION = url;
	}

	public DemoService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DemoService() {
		super(DEMOSERVICE_WSDL_LOCATION, new QName("http://yourcompany.com/",
				"demoService"));
	}

	/**
	 * 
	 * @return returns DemoDelegate
	 */
	@WebEndpoint(name = "demoPort")
	public DemoDelegate getDemoPort() {
		return super.getPort(new QName("http://yourcompany.com/", "demoPort"),
				DemoDelegate.class);
	}

}
