DROP TABLE AS_E_ESTIMATE

---自我评估 方案树---
CREATE TABLE AS_E_ESTIMATE(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL ,-- id,
NAME VARCHAR(50), -- 名称,
LEVEL INT, -- 等级,
PARENT INT, -- 父id,
);

---数据
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('审核性评估',1,0)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('定位与目标',2,1)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('办学定位',3,2)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('培养目标',3,2)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('教学中心定位',3,2)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('师资队伍',2,1)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('数量与结构',3,6)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('教育教学水平',3,6)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('教师教学投入',3,6)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('教师发展与服务',3,6)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('教学资源',2,1)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('教学经费',3,11)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('教学设施',3,11)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('专业设置与培养方案',3,11)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('课程资源',3,11)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('社会资源',3,11)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('培养过程',2,1)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('课堂教学',3,17)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('实践教学',3,17)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('第二课堂',3,17)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('教学改革',3,17)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('学生发展',2,1)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('招生及生源情况',3,22)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('学生指导与服务',3,22)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('学风与学习效果',3,22)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('就业与发展',3,22)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('质量保障',2,1)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('教学质量保障体系',3,27)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('质量信息及利用',3,27)
INSERT INTO AS_E_ESTIMATE (NAME,LEVEL,PARENT) VALUES('质量改进',3,27)


---保存ckeditor内容表
CREATE TABLE AS_E_CKEDITORCONTENT(
ID INT PRIMARY KEY IDENTITY(1,1),
CONTENT VARCHAR(5000),
EID INT)

---图片
CREATE TABLE TQC_VIEW_PIC(
VPID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PICNAME VARCHAR(200),
TYPE VARCHAR(50),
RTID INT,
paths VARCHAR(200)
)