package com.yourcompany;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "demoDelegate", targetNamespace = "http://yourcompany.com/")
public interface DemoDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "MyHelloworld")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "MyHelloworld", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.MyHelloworld")
	@ResponseWrapper(localName = "MyHelloworldResponse", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.MyHelloworldResponse")
	public String myHelloworld(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "InsertAnswerquestionInfoFromList")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "InsertAnswerquestionInfoFromList", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.InsertAnswerquestionInfoFromList")
	@ResponseWrapper(localName = "InsertAnswerquestionInfoFromListResponse", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.InsertAnswerquestionInfoFromListResponse")
	public String insertAnswerquestionInfoFromList(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "InsertTeacherInfoFromList")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "InsertTeacherInfoFromList", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.InsertTeacherInfoFromList")
	@ResponseWrapper(localName = "InsertTeacherInfoFromListResponse", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.InsertTeacherInfoFromListResponse")
	public String insertTeacherInfoFromList(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "InsertListIntoCourse")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "InsertListIntoCourse", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.InsertListIntoCourse")
	@ResponseWrapper(localName = "InsertListIntoCourseResponse", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.InsertListIntoCourseResponse")
	public String insertListIntoCourse(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "InsertSelfStudyList")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "InsertSelfStudyList", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.InsertSelfStudyList")
	@ResponseWrapper(localName = "InsertSelfStudyListResponse", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.InsertSelfStudyListResponse")
	public String insertSelfStudyList(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "LogInVaild")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "LogInVaild", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.LogInVaild")
	@ResponseWrapper(localName = "LogInVaildResponse", targetNamespace = "http://yourcompany.com/", className = "com.yourcompany.LogInVaildResponse")
	public String logInVaild(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
